#!/bin/sh
set -e

case "$1" in
purge)
	if command -v deb-systemd-helper >/dev/null 2>&1; then
		deb-systemd-helper purge vreflinkd.service >/dev/null || true
	fi
	if command -v systemctl >/dev/null 2>&1; then
		systemctl --system daemon-reload >/dev/null || true
	fi
	;;
remove)
	if command -v systemctl >/dev/null 2>&1; then
		systemctl --system daemon-reload >/dev/null || true
	fi
	;;
esac

exit 0
